- name: kde plasma desktop
  apt:
    name:
      - task-kde-desktop
      - sddm-theme-debian-breeze
      - cups
    state: latest # noqa package-latest


## Bug #698504
- name: allow print job management
  replace:
    dest: "/etc/cups/cups-files.conf"
    regexp: '^(SystemGroup lpadmin)$'
    replace: '\1 root'

- name: enable splash screen
  replace:
    dest: "/etc/default/grub"
    regexp: '"quiet"$'
    replace: '"quiet splash"'
  notify: update grub
