- name: move /etc/network/interfaces away
  command:
    cmd: mv /etc/network/interfaces /etc/network/interfaces_orig
    creates: /etc/network/interfaces_orig

- name: switch to systemd-networkd
  copy:
    src: all-eth.network
    dest: /etc/systemd/network/all-eth.network
    mode: 0644
  notify: "start and enable systemd-networkd"

# - name: install static configuration for networkd
#   template:
#     src: 20-static.network.j2
#     dest: /etc/systemd/network/20-static.network
#   notify: "enable systemd-networkd"

- name: enable local stub resolver
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    follow: false
    force: true
  notify: "start and enable systemd-resolved"
