---
# Useful for testing ..... 

- name: apply a minimal configuration for graphic gui to the machine
  hosts: all
  remote_user: ansible
  become: true
 
  roles:
    - up2date_debian
    - setup
    - gnome
