---
- name: Create a new disabled user without a password
  hosts: all
  become: yes
  tasks:
    - name: Add a new user in a disabled state
      user:
        name: ekf
        comment: "Test User"
        shell: /bin/bash
        state: present
        password: "*"

    - name: Automatic login user ekf 
      ansible.builtin.lineinfile:
        path: /etc/gdm3/daemon.conf
        regexp: '^(#\s*)?\s*AutomaticLogin=.*'
        line: 'AutomaticLogin=ekf'
      become: true  
