---
- name: Configure GNOME settings
  become: yes
  hosts: all
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install psutil
      apt:
        name: python3-psutil
        state: present
        
    - name: Set German and US keyboard layouts
      community.general.dconf:
        key: /org/gnome/desktop/input-sources/sources
        value: "[('xkb', 'de'), ('xkb', 'us')]"
        state: present
        
    - name: Set screen dimming settings
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/power/idle-dim
        value: true
        state: present
  
    - name: Disable sleep
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout
        value: 0
        state: present
        
    - name: Disable sleep
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout
        value: 0
        state: present

    - name: Disable screen sleep
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/power/sleep-display-ac
        value: false
        state: present
