---
- name: Erstelle Debian Live-CD mit toram
  hosts: all
  become: yes
  remote_user: ansible
  tasks:
    - name: Installiere notwendige Pakete
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - live-build
        - syslinux
        - isolinux
        - squashfs-tools
        - xorriso
        - grub-pc-bin
        - grub-efi-amd64-bin
        - grub-efi-ia32-bin
        - mtools
        - dosfstools

    - name: Erstelle Verzeichnis für Live-System
      file:
        path: /home/{{ ansible_user }}/live-debian
        state: directory

    - name: Initialisiere Live-Build-System
      command: >
        lb config noauto
        --clean
        --cache false
        --net-tarball false
        --ignore-system-defaults
        --distribution bookworm
        --binary-images netboot
        --mode debian
        --backports true
        --linux-packages linux-image
        --archive-areas "main non-free-firmware contrib non-free"
      args:
        chdir: /home/{{ ansible_user }}/live-debian
        
    - name: Baue das Live-System
      command: lb build
      args:
        chdir: /home/{{ ansible_user }}/live-debian
