- name: Build Debian Live CD
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install live-build
      ansible.builtin.apt:
        name: live-build
        state: present

    - name: Create build directory
      ansible.builtin.file:
        path: /home/ansible/live-build
        state: directory

    - name: Configure live-build
      ansible.builtin.command:
        cmd: lb config
        chdir: /home/ansible/live-build

    - name: Build the live CD
      ansible.builtin.command:
        cmd: lb build
        chdir: /home/ansible/live-build
