---
- name: Erstelle Debian Live-CD mit toram
  hosts: all
  become: yes
  tasks:
    - name: Installiere notwendige Pakete
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - live-build
        - syslinux
        - isolinux
        - squashfs-tools
        - xorriso
        - grub-pc-bin
        - grub-efi-amd64-bin
        - grub-efi-ia32-bin
        - mtools
        - dosfstools

    - name: Erstelle Verzeichnis für Live-System
      file:
        path: /home/{{ ansible_user }}/live-debian
        state: directory

    - name: Initialisiere Live-Build-System
      command: lb config
      args:
        chdir: /home/{{ ansible_user }}/live-debian

    - name: Füge toram zu den Boot-Parametern hinzu
      lineinfile:
        path: /home/{{ ansible_user }}/live-debian/config/bootloaders/grub-pc/live.cfg
        line: "  linux /live/vmlinuz boot=live toram"

    - name: Baue das Live-System
      command: lb build
      args:
        chdir: /home/{{ ansible_user }}/live-debian
