---
- name: Configure GNOME settings
  hosts: all
  
  tasks:
    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes

    - name: Install psutil
      become: yes
      apt:
        name: python3-psutil
        state: present
        
    - name: Set German and US keyboard layouts
      community.general.dconf:
        key: /org/gnome/desktop/input-sources/sources
        value: "[('xkb', 'de'), ('xkb', 'us')]"
        state: present
        
    - name: Set screen dimming settings
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/power/idle-dim
        value: true
        state: present
  
    - name: Disable sleep
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout
        value: 0
        state: present
        
    - name: Disable sleep
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout
        value: 0
        state: present

    - name: Disable screen sleep
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/power/sleep-display-ac
        value: false
        state: present

    - name: Set idle delay to never (disable screen blanking)
      command: gsettings set org.gnome.desktop.session idle-delay 0

    - name: Set ony term in favorites
      command: gsettings set org.gnome.shell favorite-apps "['org.gnome.Terminal.desktop']"

    - name: Damit man auch mit dem Griff runterfahren kann ohne 60s zu warten.
      command: gsettings set org.gnome.SessionManager logout-prompt "false" 

    - name: power button interaktiv
      command: gsettings set org.gnome.settings-daemon.plugins.power power-button-action 'interactive'

    - name: do not sleep 
      command: gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type "nothing" 

