---
- name: Restart computer
  hosts: all
  become: yes

  roles:
    - setup
    - up2date_debian
    - testmenu

  tasks:
    - name: Run uptime command
      command: make-auto-login-console
      
    - name: Restart the computer
      command: /sbin/shutdown -r now
      become: yes
      async: 1
      poll: 0
      ignore_errors: true
