---
# Useful for testing with menu and preseeding ..... 

- name: apply a minimal test configuration to the machine
  hosts: all
  remote_user: ansible
  become: true
 
  roles:
    - up2date_debian
    - role: testmenu
      when: enable_testmenu_role | default(true)

#      when: not enable_testmenu_role | default(true)
