---
# Useful for testing with menu and preseeding ..... 

- name: apply a minimal test configuration to the machine
  hosts: all
  remote_user: ansible
  become: true
  - name: Assemble boot parameters
      set_fact:
        boot_parameters: >-
          auto=true
          domain={{ target_domain }}
          hostname={{ target_hostname }}
          net.ifnames=0
          netcfg/choose_interface={{ target_nic }}
          priority=critical

  roles:
    - up2date_debian
    - testmenu
