---
# Useful for testing preseeding ..... 

- name: apply a test configuration to the machine
  hosts: all
  remote_user: ansible
 
  roles:
    - setup
    - up2date_debian
    - gnome4test
    # - add4gnome4test4user # must be called if gnome and user is up and running.
