---
# Useful for testing with menu and preseeding ..... 

- name: apply a test configuration to the machine
  hosts: all
  remote_user: ansible
  become: true
 
  roles:
    - setup
    - up2date_debian
    - gnome4test
    - testmenu
