---
# Useful for testing preseeding ..... 

- name: apply a test configuration to the machine
  hosts: all
  remote_user: ansible
  become: true

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
      
    - name: Wait for network to be up
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 1
        timeout: 30
      delegate_to: localhost
 
  roles:
    - setup
    - up2date_debian
    - testmenu
    - gnome4test  # - gnome 
