---
- name: Configure GNOME Classic Mode
  hosts: all
  become: yes

  tasks:
    - name: Install psutil
      apt:
        name: python3-psutil
        state: present
        
    - name: Ensure GNOME Classic Mode is installed
      apt:
        name: gnome-session-flashback
        state: present
      when: ansible_os_family == "Debian"

    - name: Set GNOME Classic as default session
      community.general.dconf:
        key: /org/gnome/desktop/session/session-name
        value: 'gnome-flashback'
        state: present
