---
- name: Install GNOME Classic on Debian
  hosts: localhost
  become: yes
  tasks:
    - name: Install GNOME Classic
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - gnome-session-flashback
        - gnome-panel
        - gnome-applets
        - gnome-flashback
        - gnome-terminal
        - nautilus
        - gdm3

    - name: Create Terminal Desktop Entry
      copy:
        dest: /usr/share/applications/gnome-terminal.desktop
        content: |
          [Desktop Entry]
          Name=Terminal
          Comment=Use the command line
          Exec=gnome-terminal
          Icon=utilities-terminal
          Terminal=false
          Type=Application
          Categories=Utility;TerminalEmulator;
          Keywords=shell;prompt;command;commandline;cmd;
