---
- name: Install GNOME Classic on Debian
  hosts: localhost
  become: yes
  tasks:
    - name: Install GNOME Classic
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - gnome-session-flashback
        - gnome-panel
        - gnome-applets
        - gnome-flashback
        - gnome-terminal
        - nautilus
        - gdm3
- name: Configure GNOME Classic Mode
  hosts: all
  become: yes
