---
# This playbook does almost nothing.  Useful for testing only preseeding.

- name: apply a minimal configuration with kerberos LAN integration
  hosts: all
  remote_user: ansible
  become: true
  roles:
    - up2date_debian
    - lanclient
