---
- name: Install Proxmox VE on Debian Bookworm
  hosts: all
  become: yes

  vars:
    ## This interface provides the default route:
    if_lan: "{{ ansible_default_ipv4.interface }}"
    if_wan: "{{ ansible_interfaces | difference([if_lan, 'lo']) | first }}"
  
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Set the hostname
      hostname:
        name: pve01.example.com

    - name: Add Proxmox VE repository key
      apt_key:
        url: "https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg" 
        state: present
    
    - name: Add Proxmox VE repository
      apt_repository:
        repo: "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription" 
        state: present

    - name: Install Proxmox VE and dependencies
      apt:
        name:
          - proxmox-ve
          - postfix
          - open-iscsi
          - chrony
        state: present

    - name: Remove Debian kernel
      apt:
        name: 'linux-image-amd64'
        state: absent
        autoremove: yes
        
    - name: Configure static IP address
      copy:
        dest: /etc/network/interfaces.d/{{ lan }}
        content: |
          auto {{ lan }} 
          iface {{ lan }} inet static
          address 192.168.4.114
          netmask 255.255.255.0
             
    - name: Reboot the server
      reboot:
        msg: "Rebooting after Proxmox VE installation"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
