---
- name: Install Proxmox VE on Debian Bookworm
  hosts: all
  become: yes

  vars:
    ## This interface provides the default route:
    if_lan: "{{ ansible_default_ipv4.interface }}"
    if_wan: "{{ ansible_interfaces | difference([if_lan, 'lo']) | first }}"

    ipaddr_lan: 172.21.122.56
  
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installi dendencies
      apt:
        name:
          - gpg
        state: present

    - name: Add Proxmox VE repository key
      apt_key:
        url: "https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg" 
        state: present
    
    - name: Add Proxmox VE repository
      apt_repository:
        repo: "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription" 
        state: present

    - name: Install Proxmox VE and dependencies
      apt:
        name:
          - proxmox-ve
          - postfix
          - open-iscsi
          - chrony
        state: present

    - name: Remove Debian kernel
      apt:
        name: 'linux-image-amd64'
        state: absent
        autoremove: yes
        
    - name: Configure static IP address
      copy:
        dest: /etc/network/interfaces
        content: |
          auto lo
          iface lo inet loopback

          auto {{ if_lan }}
          iface {{ if_lan }} inet manual

          auto vmbr0
          iface vmbr0 inet static
              address {{ ipaddr_lan }}/24 
              netmask 255.255.255.0
              bridge_ports {{ if_lan }}
              bridge_stp off
              bridge_fd 0

    - name: Configure host file
      copy:
        dest: /etc/hosts
        content: |
          127.0.0.1       localhost
          {{ ipaddr_lan }} prox4m1.proxmox.com prox4m1
          # The following lines are desirable for IPv6 capable hosts
          ::1     localhost ip6-localhost ip6-loopback
          ff02::1 ip6-allnodes
          ff02::2 ip6-allrouters

    - name: Set the hostname
      hostname:
        name: pve01.example.com
             
    - name: Reboot the server
      command: /sbin/shutdown -r now
      become: yes
      async: 1
      poll: 0
      ignore_errors: true
