---
- name: Install Proxmox VE with special kernel
  hosts: all
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - wget
          - gnupg
          - apt-transport-https
        state: present

    - name: Add Proxmox VE repository
      apt_repository:
        repo: 'deb http://download.proxmox.com/debian/pve buster pve-no-subscription'
        state: present

    - name: Add Proxmox VE repository key
      apt_key:
        url: 'http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg'
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Proxmox VE
      apt:
        name: proxmox-ve
        state: present

    - name: Install Proxmox special kernel
      apt:
        name: pve-kernel-6.8
        state: present

    - name: Reboot the server
      reboot:
        msg: "Rebooting after Proxmox VE and kernel installation"
        pre_reboot_delay: 10
        post_reboot_delay: 30
