---
# Useful for testing with menu and preseeding ..... 

- name: apply a test configuration to the machine
  hosts: all
  remote_user: ansible
  become: true

  pre_tasks:
  - name: Wait for network interface
    command: ip link show {{ ansible_default_ipv4.interface }}
    register: result
    until: "'state UP' in result.stdout"
    retries: 10
    delay: 5
  
  roles:
    - setup
    - up2date_debian
    - auto_consol_login
    - testmenu
