---
# Useful for testing with menu and preseeding ..... 

- name: apply a test configuration to the machine
  hosts: all
  remote_user: ansible
  become: true
  vars:
    my_variable: ""
  
  pre_tasks:
    - name: Wait for ansible_default_ipv4.interface to be valid
      wait_for:
        timeout: 300  # Maximum time to wait in seconds
        delay: 10     # Time to wait between checks in seconds
        state: started
      until: ansible_default_ipv4.interface is defined and ansible_default_ipv4.interface != ""
      register: result
      
  - name: Wait for network interface
    command: ip link show "
    register: result
    until: "'state UP' in result.stdout"
    retries: 10
    delay: 5
  
  roles:
    - setup
    - up2date_debian
    - auto_consol_login
    - testmenu
