---
# Useful for testing with menu and preseeding ..... 

- name: apply a test configuration to the machine
  hosts: all
  remote_user: ansible
  become: true
  
  pre_tasks:
    - name: Get adapter
      set_fact: 
        adapter: '{{ item }}'
      loop: '{{ ansible_facts.interfaces }}'
      when: 'item.startswith("enp")' 

    - name: Wait for network interface to be up
      command: ip link show "{{ adapter }}"
      register: result
      until: "'state UP' in result.stdout"
      retries: 10
      delay: 1
 
    - name: Gather facts
      ansible.builtin.setup:
      
    - name: Wait for network to be up
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 1
        timeout: 30
      delegate_to: localhost
 
  roles:
    - setup
    - up2date_debian
    - auto_consol_login
    - testmenu
