## DHCPv6, RAs and TFTP
---
- name: preseed aftpd
  debconf:
    name: atftpd
    question: atftpd/basedir
    value: /var/lib/tftpboot
    vtype: string

- name: install di-netboot-assistant and installer package
  apt:
    name:
      - kea-dhcp6-server
      - radvd
      - atftpd
    state: latest # noqa package-latest

- name: configure radvd
  template:
    src: radvd.conf.j2
    dest: /etc/radvd.conf
    mode: 0644
  notify: restart radvd

- name: configure kea-dhcp-server
  template:
    src: kea-dhcp6.conf.j2
    dest: /etc/kea/kea-dhcp6.conf
    mode: 0644
  notify: restart kea-dhcp6-server

- name: set IPv6 address on interface
  blockinfile:
    path: /etc/network/interfaces
    block: |
      allow-hotplug {{ if_lan }}
      iface {{ if_lan }} inet6 static
         address 2001:db8:b001::1/64
  notify: reconfigure network
