#!/bin/sh

set -e

lb config noauto \
	--clean \
	--cache false \
	--net-tarball false \
	--ignore-system-defaults \
	--distribution bookworm \
	--binary-images netboot \
	--mode debian \
	--backports true \
	--linux-packages linux-image \
	--archive-areas "main non-free-firmware contrib non-free" \
"${@}"
