- name: make sure ansible is available
  apt:
    name: ansible
    state: latest # noqa package-latest

- name: Generate SSH key
  ansible.builtin.openssh_keypair:
    path: /home/ansible/.ssh/id_rsa
    type: rsa
    size: 2048
    owner: ansible
    group: ansible
    mode: '0600'
    state: present
  become: yes
  become_user: ansible

- name: slurp public key
  slurp:
    src: "/home/{{ ansible_user }}/.ssh/id_rsa.pub"
  register: sshpubkey

# The following seems to be necessary to get rid of a newline:
- name: define variable
  set_fact:
    sshpubkey: "{{ sshpubkey['content'] | b64decode | replace('\n', '') }}"

- name: enable backports in preseed file
  replace:
    dest: "{{ tftp_root }}/d-i/{{ di_dist }}/preseed.cfg"
    regexp: '^#(apt-setup-udeb.*)$'
    replace: '\1'

- name: preseed client - add firmware-linux, ansible and git network-manager only once
  replace:
    dest: "{{ tftp_root }}/d-i/{{ di_dist }}/preseed.cfg"
    regexp: '^(d-i pkgsel/include string firmware-linux ansible git)$'
    replace: '#\1\nd-i pkgsel/include string firmware-linux ansible git network-manager'
