- name: Include tasks from another file
  ansible.builtin.include_tasks: 10-prepare.yml

- name: Include tasks from another file
  ansible.builtin.include_tasks: 30-preseed.yml

# Please edit default and timeout in default var file.
- name: add pxe boot entries to di-netboot-assistant
  blockinfile:
    dest: /etc/di-netboot-assistant/pxelinux.HEAD
    insertbefore: EOF
    block: |
      {{ prep_default | default('DEFAULT demohost') }}
      {{ prep_timeout | default('# TIMEOUT 100') }}
      # Use a temporary package cache during installation, install etckeeper.
      LABEL tmp pkg cache
         MENU LABEL Debian stable (amd64) + temporary package cache
         kernel ::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux
         append initrd=::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz mirror/http/proxy?=http://{{ ansible_hostname }}:3142/ pkgsel/include=etckeeper preseed/late_command="rm -fv /target/etc/apt/apt.conf" ---

      LABEL newhost
         MENU LABEL newhost no playbook / Debian {{ di_version }} (amd64) 
         kernel ::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux
         append initrd=::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz hostname=newhost interface=auto auto=true priority=critical url=tftp://{{ ansible_hostname }} ---

      LABEL demohost
         MENU LABEL demohost + playbook / Debian {{ di_version }} (amd64) 
         kernel ::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux
         append initrd=::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz hostname=demohost interface=auto auto=true priority=critical url=tftp://{{ ansible_hostname }} playbook=demohost.yml ---

      LABEL testhost
         MENU LABEL testhost + playbook Debian {{ di_version }} (amd64)  
         kernel ::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux
         append initrd=::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz hostname=testhost interface=auto auto=true priority=critical url=tftp://{{ ansible_hostname }} playbook=testhost.yml ---

      LABEL demohost1
         MENU LABEL Debian {{ di_version }} (amd64) + preseed playbook demohost1
         kernel ::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux
         append initrd=::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz hostname=demohost1 interface=auto auto=true priority=critical url=tftp://{{ ansible_hostname }} playbook=demohost.yml ---

      LABEL gnomehost
         MENU LABEL Debian {{ di_version }} (amd64) + preseed playbook gnomehost
         kernel ::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux
         append initrd=::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz hostname=gnomehost interface=auto auto=true priority=critical url=tftp://{{ ansible_hostname }} playbook=gnomehost.yml ---  

      LABEL minihost
         MENU LABEL Debian {{ di_version }} (amd64) + preseed playbook  minihost
         kernel ::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux
         append initrd=::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz hostname=minihost interface=auto auto=true priority=critical url=tftp://{{ ansible_hostname }} playbook=minihost.yml ---

      LABEL installbox1
         MENU LABEL Debian {{ di_version }} (amd64) + preseed installbox1 
         kernel ::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux
         append initrd=::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz hostname=installbox1 interface=auto auto=true priority=critical url=tftp://{{ ansible_hostname }} playbook=installbox.yml ---

      LABEL installbox2
         MENU LABEL Debian {{ di_version }} (amd64) + preseed installbox2
         kernel ::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux
         append initrd=::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz hostname=installbox2 interface=auto auto=true priority=critical url=tftp://{{ ansible_hostname }} playbook=installbox.yml ---

      LABEL kiosk
         MENU LABEL Debian {{ di_version }} (amd64) + preseed + kiosk.yml (playbook does not work so)
         kernel ::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux
         append initrd=::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz hostname=kiosk auto=true priority=critical url=tftp://{{ ansible_hostname }} playbook=kiosk.yml ---

      LABEL cloudbox
         MENU LABEL Debian {{ di_version }} (amd64) + preseed + cloudbox.yml (playbook does not work so)
         kernel ::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux
         append initrd=::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz hostname=cloudbox auto=true priority=critical url=tftp://{{ ansible_hostname }} playbook=cloudbox.yml ---

      LABEL edubox
         MENU LABEL Debian {{ di_version }} (amd64) + preseed + edubox.yml (playbook does not work so)
         kernel ::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux
         append initrd=::/d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz hostname=edubox auto=true priority=critical url=tftp://{{ ansible_hostname }} playbook=edubox.yml ---

         #LABEL daily
         #MENU LABEL Debian daily (amd64) + preseed + kiosk.yml
         #kernel ::/d-i/n-a/daily/amd64/linux
         #append initrd=::/d-i/n-a/daily/amd64/initrd.gz auto=true priority=critical url=tftp://{{ ansible_hostname }} playbook=kiosk.yml ---
    marker: "# {mark} ANSIBLE MANAGED BLOCK default"
  notify: "rebuild di-netboot-assistant menu"

# Please edit default and timeout in default var file.
- name: add efi boot entries to di-netboot-assistant
  blockinfile:
    dest: /etc/di-netboot-assistant/grub.cfg.HEAD
    insertbefore: EOF
    block: |
      {{ prep_default_efi | default("set default='Debian preseed demohost.yml'") }}
      {{ prep_timeout_efi | default('# set timeout=10') }}

      # Use a temporary package cache during installation, install etckeeper.
      menuentry 'Debian stable (amd64) + temporary package cache' {
         linux   /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux \
                   mirror/http/proxy?=http://{{ ansible_hostname }}:3142/ pkgsel/include=etckeeper \
                   preseed/late_command="rm -fv /target/etc/apt/apt.conf" ---
         initrd  /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz
      }

      menuentry 'Debian preseed ohne playbook' {
         linux   /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux \
                   hostname=newhost auto=true interface=auto priority=critical \
                   url=tftp://{{ ansible_hostname }} ---
         initrd  /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz
      }

      menuentry 'Debian preseed minimal.yml' {
         linux   /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux \
                   hostname=minimal auto=true interface=auto priority=critical \
                   url=tftp://{{ ansible_hostname }} playbook=minimal.yml ---
         initrd  /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz
      }

      menuentry 'Debian preseed demohost.yml' {
         linux   /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux \
                   hostname=demohost auto=true interface=auto priority=critical \
                   url=tftp://{{ ansible_hostname }} playbook=demohost.yml ---
         initrd  /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz
      }

      menuentry 'Debian preseed testhost.yml' {
         linux   /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux \
                   hostname=testhost auto=true interface=auto priority=critical \
                   url=tftp://{{ ansible_hostname }} playbook=testhost.yml ---
         initrd  /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz
      }

      menuentry 'Debian preseed gnomehost.yml' {
        linux   /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux \
                  hostname=gnomehost auto=true interface=auto priority=critical \
                  url=tftp://{{ ansible_hostname }} playbook=gnomehost.yml ---
        initrd  /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz
      }

      menuentry 'Debian preseed installbox1' {
        linux   /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux \
                  hostname=installbox1 auto=true interface=auto priority=critical \
                  url=tftp://{{ ansible_hostname }} playbook=installbox.yml ---
        initrd  /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz
      }

       menuentry 'Debian preseed installbox2' {
        linux   /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux \
                  hostname=installbox2 auto=true interface=auto priority=critical \
                  url=tftp://{{ ansible_hostname }} playbook=installbox.yml ---
        initrd  /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz
      }

      menuentry 'Debian preseed + kiosk.yml' {
         linux   /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux \
                   hostname=kiosk auto=true priority=critical \
                   url=tftp://{{ ansible_hostname }} playbook=kiosk.yml ---
         initrd  /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz
      }

      menuentry 'Debian preseed + cloudbox.yml' {
         linux   /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux \
                   hostname=cloudbox auto=true priority=critical \
                   url=tftp://{{ ansible_hostname }} playbook=cloudbox.yml ---
         initrd  /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz
      }

      menuentry 'Debian preseed + edubox.yml' {
         linux   /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/linux \
                   hostname=edubox auto=true priority=critical \
                   url=tftp://{{ ansible_hostname }} playbook=edubox.yml ---
         initrd  /d-i/n-pkg/images/{{ di_version }}/amd64/text/debian-installer/amd64/initrd.gz
      }

      #menuentry 'Debian daily (amd64) + preseed + kiosk.yml' {
      #   linux   /d-i/n-a/daily/amd64/linux auto=true priority=critical \
      #             url=tftp://{{ ansible_hostname }} playbook=kiosk.yml ---
      #   initrd  /d-i/n-a/daily/amd64/initrd.gz
      #}
    marker: "# {mark} ANSIBLE MANAGED BLOCK default"
  notify: "rebuild di-netboot-assistant menu"

- name: Include tasks from another file
  ansible.builtin.include_tasks: 90-finish.yml