- name: Include tasks from another file
  ansible.builtin.include_tasks: 10-prepare.yml

- name: Include tasks from another file
  ansible.builtin.include_tasks: 30-preseed.yml

- name: Include tasks from another file
  ansible.builtin.include_tasks: 70-menues.yml

- name: Include tasks from another file
  ansible.builtin.include_tasks: 90-finish.yml