- name: Install GNOME Classic
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - gnome-session-flashback
    - gnome-panel
    - gnome-applets
    - gnome-flashback
    - gnome-terminal
    - nautilus
    - gdm3
  become: true  

- name: make sure /etc/dconf/profile/ exists
  file:
    path: /etc/dconf/profile/
    state: directory
    recurse: true
  become: true

- name: prepare for gnome customized defaults
  copy:
    src: user
    dest: /etc/dconf/profile/user
    mode: 0644
  become: true  
  notify: update dconf
  
- name: make sure /etc/dconf/db/local.d/ exists
  file:
    path: /etc/dconf/db/local.d/
    state: directory
    recurse: true
  become: true

- name: modify gnome defaults
  copy:
    src: defaults
    dest: /etc/dconf/db/local.d/defaults
    mode: 0644
  become: true  
  notify: update dconf

- name: disable splash screen
  replace:
    dest: "/etc/default/grub"
    regexp: '"quiet"$'
    replace: '" "'
  become: true  
  notify: update grub

- name: Create autostart directory if it doesn't exist
  file:
    path: /home/{{ ansible_user }}/.config/autostart
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: true  

- name: Create GNOME Terminal autostart .desktop file
  copy:
    content: |
      [Desktop Entry]
      Type=Application
      Name=GNOME Terminal
      Exec=gnome-terminal
      OnlyShowIn=GNOME;
      X-GNOME-Autostart-enabled=true
    dest: /home/{{ ansible_user }}/.config/autostart/gnome-terminal.desktop
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: true  

- name: Replace a localhost entry searching for a literal string to avoid escaping
  ansible.builtin.lineinfile:
    path: /etc/gdm3/daemon.conf
    regexp: '#.*AutomaticLoginEnable'
    line: AutomaticLoginEnable=True
  become: true
  
- name: Replace a localhost entry searching for a literal string to avoid escaping
  ansible.builtin.lineinfile:
    path: /etc/gdm3/daemon.conf
    regexp: '#.*AutomaticLogin'
    line: AutomaticLogin={{ ansible_user }}
  become: true  
  notify: Restart GDM
    
- name: Ensure gnome-initial-setup is removed
  apt:
    name: gnome-initial-setup
    state: absent
  become: true
