# - name: gnome hibernate by default
#   apt: name=gnome-shell-extension-suspend-button state=latest # noqa package-latest

- name: gnome desktop
  apt:
    name:
      - task-gnome-desktop
      - gnome-shell-extension-dashtodock
      - cups
    state: latest # noqa package-latest
#    - gnome-shell-extension-desktop-icons

- name: make sure /etc/dconf/profile/ exists
  file:
    path: /etc/dconf/profile/
    state: directory
    recurse: true

- name: prepare for gnome customized defaults
  copy:
    src: user
    dest: /etc/dconf/profile/user
    mode: 0644
  notify: update dconf

- name: make sure /etc/dconf/db/local.d/ exists
  file:
    path: /etc/dconf/db/local.d/
    state: directory
    recurse: true

- name: modify gnome defaults
  copy:
    src: defaults
    dest: /etc/dconf/db/local.d/defaults
    mode: 0644
  notify: update dconf

- name: configure gdm3
  replace:
    dest: /etc/gdm3/greeter.dconf-defaults
    regexp: "{{ item.rex }}"
    replace: "{{ item.rep }}"
  loop:
    - rex: "# disable-user-list=.*"
      rep: "disable-user-list=true"
    - rex: "# sleep-inactive-ac-timeout=.*"
      rep: "sleep-inactive-ac-timeout=600"
    - rex: "# sleep-inactive-ac-type=.*"
      rep: "sleep-inactive-ac-type='interactive'\npower-button-action='interactive'"

## Bug #698504
- name: allow print job management
  replace:
    dest: "/etc/cups/cups-files.conf"
    regexp: '^(SystemGroup lpadmin)$'
    replace: '\1 root'

- name: enable splash screen
  replace:
    dest: "/etc/default/grub"
    regexp: '"quiet"$'
    replace: '" "'
  notify: update grub



- name: Create autostart directory if it doesn't exist
  file:
    path: /home/{{ ansible_user }}/.config/autostart
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create GNOME Terminal autostart .desktop file
  copy:
    content: |
      [Desktop Entry]
      Type=Application
      Name=GNOME Terminal
      Exec=gnome-terminal
      OnlyShowIn=GNOME;
      X-GNOME-Autostart-enabled=true
    dest: /home/{{ ansible_user }}/.config/autostart/gnome-terminal.desktop
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'


- name: Ensure GDM custom.conf file exists
  copy:
    content: |
      [daemon]
      AutomaticLoginEnable=True
      AutomaticLogin={{ ansible_user }}
    dest: /etc/gdm/custom.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart GDM to apply changes
  systemd:
    name: gdm
    state: restarted