- name: gnome desktop
  apt:
    name:
      - task-gnome-desktop
    state: latest # noqa package-latest

- name: make sure /etc/dconf/profile/ exists
  file:
    path: /etc/dconf/profile/
    state: directory
    recurse: true

- name: prepare for gnome customized defaults
  copy:
    src: user
    dest: /etc/dconf/profile/user
    mode: 0644
  notify: update dconf

- name: make sure /etc/dconf/db/local.d/ exists
  file:
    path: /etc/dconf/db/local.d/
    state: directory
    recurse: true

- name: modify gnome defaults
  copy:
    src: defaults
    dest: /etc/dconf/db/local.d/defaults
    mode: 0644
  notify: update dconf

- name: disable splash screen
  replace:
    dest: "/etc/default/grub"
    regexp: '"quiet"$'
    replace: '" "'
  notify: update grub

- name: Create autostart directory if it doesn't exist
  file:
    path: /home/{{ ansible_user }}/.config/autostart
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create GNOME Terminal autostart .desktop file
  copy:
    content: |
      [Desktop Entry]
      Type=Application
      Name=GNOME Terminal
      Exec=gnome-terminal
      OnlyShowIn=GNOME;
      X-GNOME-Autostart-enabled=true
    dest: /home/{{ ansible_user }}/.config/autostart/gnome-terminal.desktop
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Insert auto login
  ansible.builtin.lineinfile:
    path: /etc/gdm3/daemon.conf
    regexp: '^[daemon]'
    insertafter: '[daemon]'
    line: AutomaticLoginEnable=True

- name: Insert auto login
  ansible.builtin.lineinfile:
    path: /etc/gdm3/daemon.conf
    regexp: '^[daemon]'
    insertafter: '[daemon]'
    line: AutomaticLogin={{ ansible_user }} 

#- name: Restart GDM to apply changes
#  systemd:
#    name: gdm
#    state: restarted
