- name: restart slapd
  systemd: name=slapd state=restarted enabled=yes
  listen: "restart slapd"

- name: restart krb5-kdc
  systemd: name=krb5-kdc state=restarted enabled=yes
  listen: "restart krb5-kdc"

- name: restart krb5-admin-server
  systemd: name=krb5-admin-server state=restarted enabled=yes
  listen: "restart krb5-admin-server"
