- name: update dconf
  command: dconf update
  listen: update dconf
  become: true

- name: update grub
  command: update-grub
  listen: update grub
  become: true

- name: Restart GDM to apply changes
  systemd:
    name: gdm
    state: restarted
  become: true  
