---
- name: Install packages needed
  ansible.builtin.apt:
    name:
      - ansible
    state: latest

- name: Deploy script
  ansible.builtin.copy:
    src: make-auto-login-console
    dest: /usr/local/bin/
    mode: '0755'

- name: Deploy script
  ansible.builtin.copy:
    src: sudo4user
    dest: /usr/local/bin/
    mode: '0755'

- name: Deploy script
  ansible.builtin.copy:
    src: clean.sda
    dest: /usr/local/bin/
    mode: '0755'

- name: Deploy script
  ansible.builtin.copy:
    src: p
    dest: /home/ansible/
    mode: '0755'

- name: Deploy script
  ansible.builtin.copy:
    src: r
    dest: /home/ansible/
    mode: '0755'

- name: Deploy script
  ansible.builtin.copy:
    src: start-reboot
    dest: /home/ansible/
    mode: '0755'

- name: Deploy script
  ansible.builtin.copy:
    src: 900-timeout-reboot
    dest: /home/ansible/
    mode: '0755'

- name: Deploy script
  ansible.builtin.copy:
    src: start-powercycle
    dest: /home/ansible/
    mode: '0755'

- name: Deploy script
  ansible.builtin.copy:
    src: 900-timeout-powercycle
    dest: /home/ansible/
    mode: '0755'

- name: Deploy script
  ansible.builtin.copy:
    src: gen-new-hostname-ip.bash
    dest: /usr/local/bin/
    mode: '0755'

- name: Copy config file
  ansible.builtin.copy:
    src: gen-new-hostname-ip.bash
    dest: /var/lib/tftpboot/debian-installer/pxelinux.cfg/01-bc-24-11-00-00-01
    mode: '0755'

- name: Create autologin service override directory
  ansible.builtin.file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    mode: '0755'

- name: Create autologin service override file
  ansible.builtin.copy:
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --autologin ansible --noclear %I $TERM
    mode: '0644'
  notify: Restart tty1

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Ensure .bash_aliases file exists
  copy:
    dest: /home/ansible/.bash_aliases
    content: |
      alias ll='ls -la'
      alias gs='git status'
      alias gp='git pull'
      alias menu='echo $PATH | grep :.$ > /dev/null || PATH=$PATH:. && cat menu.txt'
       
- name: create a small file with instructions
  copy:
    dest: /home/ansible/menu.txt 
    content: |
      ---------------------------------------------------
      clean-sda) clean hardisk sda for new install
      p) poweroff 
      r) reboot
      clean.sda) Clean hardisk (only sda) for new Install over the net.
      Please copy 900-* to todo to get a endless test. 
      ---------------------------------------------------

- name: Add a line to .bashrc
  lineinfile:
    path: /home/ansible/.bashrc
    line: 'ip addr|grep global'
      
- name: Add a line to .bashrc
  lineinfile:
    path: /home/ansible/.bashrc
    line: 'if [ -d todo ]; then run-parts todo; else menu; fi'
    
