#!/bin/bash
#
PCIDEV="0000:00:15.0"
SMBus=$(ls -l /sys/bus/i2c/devices/ |grep ${PCIDEV} | awk '{print $9}' | grep i2c | sed 's/i2c-//' )
# scan side cards and read eeproms 
sudo i2cset -y $SMBus 0x70 1 
sudo i2cdump -y $SMBus 0x55 
sudo i2cset -y $SMBus 0x70 0 

PCIDEV="0000:00:15.1"
SMBus=$(ls -l /sys/bus/i2c/devices/ |grep ${PCIDEV} | awk '{print $9}' | grep i2c | sed 's/i2c-//' )
# scan pci bus and read eeproms 
for i in {0x70..0x77}; do
  sudo i2cset -y $SMBus $i 1 && sudo i2cdump -y $SMBus 0x55 
  sudo i2cset -y $SMBus $i 0 
done
  sudo i2cset -y $SMBus 0x76 1 && sudo i2cdump -y $SMBus 0x55 
  sudo i2cset -y $SMBus 0x76 0 

PCIDEV="0000:00:1f.4"
SMBus=$(ls -l /sys/bus/i2c/devices/ |grep ${PCIDEV} | awk '{print $9}' | grep i2c | sed 's/i2c-//' )
readonly SLEEP4ME=0.2
sudo modprobe i2c-dev
# SMBus=$(sudo i2cdetect -l |grep smbus|cut -d'-' -f2|cut  -f1)
echo "Test start:"
while true; do
  sudo i2cset -y ${SMBus} 0x2E 0xa0 0x80 b # LED
  # sudo i2cset -y ${SMBus} 0x2E 0xa0 0x04 b # Watchdog
  sleep $SLEEP4ME
  sudo i2cset -y ${SMBus} 0x2E 0xa0 0x00 b 
  sleep $SLEEP4ME
done
